### ISSUE TITLE
Monitoring a TEAM Engine test run after the first start fails

### ISSUE THREAD

**Issue by jonherrmann** [etf-validator/etf-webapp#147]
ETF fails running a TEAM engine test **after the first start**,  when **the test run is monitored**, with this exception:

> java.lang.IllegalStateException: Executable Test Suite does not possess test items
> 	at de.interactive_instruments.etf.testdriver.DefaultTestRun$RunProgress.getMaxSteps(DefaultTestRun.java:80)
> 	at de.interactive_instruments.etf.webapp.controller.TestRunController$TaskProgressDto.createCompletedMsg(TestRunController.java:136)
> 	at de.interactive_instruments.etf.webapp.controller.TestRunController.progressLog(TestRunController.java:353)

The problem occurs because the test steps are not known since they are inserted after the first test run of the ETS. This only applies to the TEAM Engine test driver.

The issue could be fixed, by inserting a dummy assertion in the [TypeLoader](https://github.com/interactive-instruments/etf-tetd/blob/master/src/main/java/de/interactive_instruments/etf/testdriver/te/TeTypeLoader.java#L298-L309), which will then be overriden after the first run.

**Comment by jonherrmann** [comment]
Fixed in [Version 2.1 ](https://github.com/etf-validator/etf-webapp/releases/tag/2.1.0)
